# Netlify configuration for John Plumber static site
# No build step; publish the repository root
[build]
  publish = "."

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets lightly to allow easy updates
[[headers]]
  for = "/*.{css,js,jpg,jpeg,png,webp,svg,ico,mp4}"
  [headers.values]
    Cache-Control = "public, max-age=86400"
